### ISSUE TITLE
Relax requirements

### ISSUE THREAD

**Issue by pySilver** [ixc/wagtail-instance-selector#1]
Please relax requirements to 2.6.2 (or upcoming 2.7 if supported)

**Comment by markfinger** [comment]
I think the deps in requirements.txt are only used for creation of a dev env, but please correct me if I'm wrong.

Are you raising this because of a specific issue, or as a general best practice not to build against a specific version?

**Comment by pySilver** [comment]
I'm raising this because Pipenv complains (cannot satisfy dependencies).

**Comment by markfinger** [comment]
How're you specifying the dependency? Are you targeting the repo or the PyPI package?

**Comment by pySilver** [comment]
Pypy package. 

```
[packages]
wagtail-instance-selector = "==1.0.1"
```
gives:

[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches wagtail<2.6,<2.7,==2.6.2,>1.4,>=1.11,>=1.11.1,>=2.1,>=2.4,>=2.6
Tried: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.4.1, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.8, 0.8.9, 0.8.9, 0.8.10, 0.8.10, 1.0, 1.0, 1.1, 1.1, 1.2, 1.2, 1.3, 1.3, 1.3.1, 1.3.1, 1.4, 1.4, 1.4.1, 1.4.1, 1.4.2, 1.4.2, 1.4.3, 1.4.3, 1.4.4, 1.4.4, 1.4.5, 1.4.5, 1.4.6, 1.4.6, 1.5, 1.5, 1.5.1, 1.5.1, 1.5.2, 1.5.2, 1.5.3, 1.5.3, 1.6, 1.6, 1.6.1, 1.6.1, 1.6.2, 1.6.2, 1.6.3, 1.6.3, 1.7, 1.7, 1.8, 1.8, 1.8.1, 1.8.1, 1.8.2, 1.8.2, 1.9, 1.9, 1.9.1, 1.9.1, 1.10, 1.10, 1.10.1, 1.10.1, 1.11, 1.11, 1.11.1, 1.11.1, 1.12, 1.12, 1.12.1, 1.12.1, 1.12.2, 1.12.2, 1.12.3, 1.12.3, 1.12.4, 1.12.4, 1.12.5, 1.12.5, 1.12.6, 1.12.6, 1.13, 1.13, 1.13.1, 1.13.1, 1.13.2, 1.13.2, 1.13.3, 1.13.3, 1.13.4, 1.13.4, 2.0, 2.0, 2.0.1, 2.0.1, 2.0.2, 2.0.2, 2.1, 2.1, 2.1.1, 2.1.1, 2.1.2, 2.1.2, 2.1.3, 2.1.3, 2.2, 2.2, 2.2.1, 2.2.1, 2.2.2, 2.2.2, 2.3, 2.3, 2.4, 2.4, 2.5, 2.5, 2.5.1, 2.5.1, 2.5.2, 2.5.2, 2.6, 2.6, 2.6.1, 2.6.1, 2.6.2, 2.6.2
Skipped pre-versions: 1.0b1, 1.0b2, 1.0b2, 1.0b2, 1.0rc1, 1.0rc1, 1.0rc2, 1.0rc2, 1.1rc1, 1.1rc1, 1.2rc1, 1.2rc1, 1.3rc1, 1.3rc1, 1.4rc1, 1.4rc1, 1.5rc1, 1.5rc1, 1.6rc1, 1.6rc1, 1.7rc1, 1.7rc1, 1.8rc1, 1.8rc1, 1.9rc1, 1.9rc1, 1.10rc1, 1.10rc1, 1.11rc1, 1.11rc1, 1.12rc1, 1.12rc1, 1.13rc1, 1.13rc1, 2.0b1, 2.0b1, 2.0rc1, 2.0rc1, 2.1rc1, 2.1rc1, 2.1rc2, 2.1rc2, 2.2rc1, 2.2rc1, 2.2rc2, 2.2rc2, 2.3rc1, 2.3rc1, 2.3rc2, 2.3rc2, 2.4rc1, 2.4rc1, 2.5rc1, 2.5rc1, 2.6rc1, 2.6rc1
There are incompatible versions in the resolved dependencies.

**Comment by pySilver** [comment]
Looks like its not an issue with you packages. Sorry for trouble.

**Comment by markfinger** [comment]
No worries. I guess it's whatever is specifying the `==2.6.2` requirement. Good luck 😄
