### ISSUE TITLE
`default_app_config` in `__init__.py` deprecated since Django 3.2

### ISSUE THREAD

**Issue by tbrlpld** [ixc/wagtail-instance-selector#23]
Since Django 3.2 it is not necessary anymore to declare a `default_app_config` is only a single app config is present in the `apps.py`. 

With that declaration, Django throws deprecation warnings like so:
```
/venv/lib/python3.8/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'instance_selector' defines default_app_config = 'instance_selector.apps.AppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

**Possible solution**

Only define `default_app_config` for Django versions before 3.2. 

```python
# __init__.py
import django 

if django.VERSION < (3, 2):
    default_app_config = "%s.apps.AppConfig" % __name__
```

***

See also
https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery

**Comment by markfinger** [comment]
Thanks for the heads up. Your proposed solution sounds perfect 👍 

Can you open a PR with the changes?

**Comment by tbrlpld** [comment]
@markfinger I have added #24 for your consideration 😄
